scg-system/src/main/java/io/telicent/core/FMod_RequestIDFilter.java, scg-system/src/main/java/io/telicent/core/SmartCacheGraph.java, scg-system/src/test/java/io/telicent/TestRequestIDFilter.java
Adding Request ID filter module to acquire the Request ID, if provided, on incoming requests and make available for logging purposes. If it's not available we create a new UUID and use that.
The code is nearly identical to SC Core's Request ID Filter ([here](https://github.com/telicent-oss/smart-caches-core/blob/main/jaxrs-base-server/src/main/java/io/telicent/smart/cache/server/jaxrs/filters/RequestIdFilter.java)) for obvious reasons.
Replacing the incorrectly name PR #5
=> [CORE-327] Adding Request ID filter module

pom.xml, scg-system/src/main/java/io/telicent/graphql/ActionTelicentGraphQL.java
This makes new limit and offset arguments available on the search query within the Telicent Graph Schema.
Also simplifies some of the GraphQL related implementation around auth token passing to take advantage of newer features in JWT Servlet Auth tht makes the users JWT available to us more cleanly.
- Adopts the new feature from telicent-oss/graphql-jena#10
- Progress on CORE-355
=> Upgrade to GraphQL 0.7.0 (CORE-355)

scg-docker/Dockerfile
Replace tini with dumb-init  as the use TINI_SUBREAPER  is causing issues where  PR_SET_CHILD_SUBREAPER is unavailable on some  platforms.
=> fix(docker): replace tini with dumb-init

scg-system/src/main/java/io/telicent/core/FMod_InitialCompaction.java, scg-system/src/main/java/io/telicent/core/FMod_RequestIDFilter.java, scg-system/src/main/java/io/telicent/core/SmartCacheGraph.java, scg-system/src/main/java/io/telicent/graphql/ActionTelicentGraphQL.java, scg-system/src/test/java/io/telicent/AbstractBearerAuthTests.java, scg-system/src/test/java/io/telicent/LibTestsSCG.java, scg-system/src/test/java/io/telicent/TestInitialCompaction.java, scg-system/src/test/java/io/telicent/TestMainSmartCacheGraph.java, scg-system/src/test/java/io/telicent/TestPersistentSetup.java, scg-system/src/test/java/io/telicent/otel/MetricsCollector.java, scg-system/src/test/java/io/telicent/platform/play/MessageRequest.java
This will ensure that the on-disk TDB2 will be compacted at server start-up. It can be disabled via environment variable should we wish to. 
Also, some minor code tidy-up. Removing some unused imports and some Commons Collection code that can be easily replaced with core code.
=> [CORE-390] Add initial load compaction module

scg-docker/Dockerfile
Add -v flag to allow for info level messages to the console
=> fix: dumb-init add verbose to allow logging info msg

scg-docker/Dockerfile
$BUILDPLATFORM — matches the current machine. (e.g. linux/amd64) only.
Causing the 'linux/arm64'  image to be reported as  `x86_64 (uname -m) ` and using the emulator as seen in `ps auxww` `/usr/bin/qemu-x86_64 /opt/java/openjdk/bin/java java ...`
it now defaults back to  `--platform=$TARGETPLATFORM`  (default value for all build stages)
=> bug: docker build multi-arch

CHANGELOG.md, pom.xml, scg-system/src/main/java/io/telicent/core/FMod_FusekiKafkaSCG.java, scg-system/src/main/java/io/telicent/core/FMod_InitialCompaction.java, scg-system/src/main/java/io/telicent/core/FMod_JwtServletAuth.java, scg-system/src/main/java/io/telicent/core/MainSmartCacheGraph.java
- Upgrade to latest dependencies
- Fix some logging statements that had incorrect/incomplete placeholders and/or unnecessary double `String.format()` calls
- Kafka Connectors are started after server startup to avoid crash restart loops (CORE-443)
- Initial compaction can now happen both before and after server startup to account for potential database bloat caused by initial Kafka load post startup, if a database is already maximally compacted it isn't compacted again after startup
=> Final preparation for a 0.82.0 release

CHANGELOG.md, scg-system/src/main/java/io/telicent/core/FMod_InitialCompaction.java, scg-system/src/main/java/io/telicent/core/SmartCacheGraph.java
Further fixes to Initial Compaction logic based on observed Crash Restart loop behaviour in our dev clusters.  There are still two opportunities for compaction but both now happen after the HTTP Server is up to avoid failing readiness probes.
=> Further improved Initial Compaction (CORE-443)

scg-docker/Dockerfile.alpine, scg-docker/docker-run.sh
By setting ROCKSDB_MUSL_LIBC flag to false. 
This tells RocksDB not to check to see what C Library exists on the image in question - by checking ldd, a unix process for listing what libraries to load for file. The flag essentially says "there is no MUSL on this machine" which is RocksDB's preferred lib (for performance reasons) and forces it to use GLIBC.
Note: if we use an Alpine image, which doesn't have GLBIC and uses MUSL instead, we would obviously set this flag to true.
I have also added a specific Dockerfile for Alpine builds (Dockerfile.alpine) should we wish to use it. The image generated is about ~150Mb smaller and could be more performant - testing is required to confirm. I have updated the docker-run.sh script so that it can take an "alpine" parameter that creates an alpine …
=> [CORE-441] Addressing potential security issue

scg-docker/Dockerfile, scg-docker/Dockerfile.alpine
Addressing dumb-init warnings by running in single-child mode.
[dumb-init] Unable to detach from controlling tty (errno=25 Inappropriate ioctl for device).
[dumb-init] Child spawned with PID 7.
[dumb-init] Unable to attach to controlling tty (errno=25 Inappropriate ioctl for device).
[dumb-init] setsid complete.
=> [CORE-537] Addressing dumb-init warnings

pom.xml
Including Fuseki Kafka 1.5.0 which has improved support for connecting to Kafka clusters that require additional configuration for things like complex AuthN mechanisms.
=> Upgrade to latest dependencies (CORE-478)

pom.xml
I just changed the yaml parser version because I want to make a new release of SCG to be able to test it. I have been unsuccessful with mounting the new fuseki-yaml-config jar in the sys-int cluster (even if I delete the statefulset I get the same permissions issues when I try to re-apply it), and testing using Rancher Desktop and k8s-desktop is insufficient because the config has to be modified to work locally. So I'm resorting to releasing SCG with the new parser version. If this is a bad idea or bad timing for a release please let me know.
=> update fuseki-yaml-parser to 1.0.4

pom.xml, scg-system/src/main/java/io/telicent/backup/services/DatasetBackupService.java, scg-system/src/main/java/io/telicent/core/TelicentKafka.java, scg-system/src/test/java/io/telicent/TestRequestIDFilter.java, scg-system/src/test/java/io/telicent/backup/services/TestDatasetBackupService.java, scg-system/src/test/java/io/telicent/core/TestInitialCompaction.java, scg-system/src/test/java/io/telicent/otel/TestJenaMetrics.java
Wrap restore operation in transaction lock to ensure that we do not invalidate the underlying data stores by processing updates. In particular, we are at risk of the kafka batch processing exposing the Rocks DB during it's transition and corrupting it.  This addresses that. 
I've tested it as best I can and am confident it works i.e. I cannot break it locally.  
I've also shored up some test coverage.
=> [CORE-649]  Safeguard Restore operation.

scg-system/src/main/java/io/telicent/backup/services/DatasetBackupService.java, scg-system/src/main/java/io/telicent/core/FMod_FusekiKafkaSCG.java, scg-system/src/main/java/io/telicent/otel/FMod_OpenTelemetry.java, scg-system/src/test/java/io/telicent/backup/services/TestDatasetBackupService.java
To avoid any complications when creating/loading the backup files.
Data set names can be in the following forms "/knowledge" or "/knowledge/upload" which can cause trouble when creating files. We remove the first '/' and replace the other (or any other troublesome characters) with more suitable variants.
=> [CORE-679] Sanitise the dataset names 

README.md, docs/labels-api.yaml, scg-docker/Dockerfile, scg-docker/docker-run.sh, scg-docker/mnt/config/config-labels-query-test.ttl, scg-docker/mnt/config/labels-query-test-attribute-store.ttl, scg-system/pom.xml, scg-system/src/main/java/io/telicent/core/SmartCacheGraph.java, scg-system/src/main/java/io/telicent/labels/FMod_LabelsQuery.java, scg-system/src/main/java/io/telicent/labels/LabelsQuery.java, scg-system/src/main/java/io/telicent/labels/TripleLabels.java, scg-system/src/main/java/io/telicent/labels/services/LabelsQueryService.java, scg-system/src/main/java/io/telicent/labels/servlets/LabelsQueryServlet.java, scg-system/src/test/files/sample-data-labelled.trig, scg-system/src/test/java/io/telicent/labels/services/ITLabelsQueryService.java, scg-system/src/test/java/io/telicent/labels/services/LabelsQueryIntegrationTest.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQuery.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQueryService.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQueryServiceRocksDB.java, scg-system/src/test/resources/config-labels-query-test.ttl, scg-system/src/test/resources/labels-query-test-attribute-store.ttl, scg-system/src/test/resources/test-data-labelled.trig
This PR adds a new admin endpoint to SCG which allows a user to retrieve the security labels for an RDF triple supplied in the request. This functionality needs to be enabled using the `ENABLE_LABELS_QUERY` environment variable. 
The PR includes API documentation and sample labelled data which can be run within a Docker container and tested locally using an OpenAPI viewer such as https://editor-next.swagger.io/.
=> CORE-412: add admin endpoint for triple label queries

docs/backups-api.yaml
=> [CORE-710] Add missing "description" parameter to Backup API documentation

scg-system/pom.xml, scg-system/src/main/java/io/telicent/labels/FMod_LabelsQuery.java, scg-system/src/main/java/io/telicent/labels/LabelsQueryRequest.java, scg-system/src/main/java/io/telicent/labels/TripleLabels.java, scg-system/src/main/java/io/telicent/labels/services/LabelsQueryService.java, scg-system/src/main/java/io/telicent/labels/servlets/LabelsQueryServlet.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQuery.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQueryService.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQueryServiceRocksDB.java
Addresses CORE-694 & CORE-695 at the same time.
We now return the incoming triple(s), can handle a list of entries and also wild cards.
To illustrate:
**Single query**
```json
{
"subject": "http://dbpedia.org/resource/London",
"predicate": "http://dbpedia.org/ontology/country",
"object": "http://dbpedia.org/resource/United_Kingdom"
}
```
**Multi query**
```json
[
{
"subject": "http://telicent.io/data#ALG12538_labor_group_algeria_actor1_participant",
"predicate": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
"object": "http://acleddata.com/ontology#Actor1Participant"
},
{
"subject": "http://telicent.io/data#ALG12538_labor_group_algeria_actor1_participant",
"predicate": "http://ies.data.gov.uk/ontology/ies4#isParticipantIn",
"object": "http://telicent.io/data#ALG12538"
},
{
"subject": …
```
=> [CORE-693] Extend Label Querying 

scg-system/src/main/java/io/telicent/core/FMod_FusekiKafkaSCG.java, scg-system/src/test/java/io/telicent/core/TestFusekiKafkaSCG.java
Fixing issues with Kafka Connections which could have additional path suffix to underlying dataset.
We have config as such:
:connector3  rdf:type         fk:Connector;
fk:configFile         "env:{KAFKA_CONFIG_FILE_PATH:}";
fk:fusekiServiceName  "/catalog/upload";
fk:replayTopic        false;
fk:stateFile          "/fuseki/databases/Replay-Catalog-RDF.state";
fk:topic              "catalog" .
for the "catalog" dataset. 
That means when looking up "/catalog" doesn't match. We need to strip that off.
=> [Minor] Strip out path for Kafka Connectors.

docs/access-api.yaml, scg-system/src/main/java/io/telicent/access/AccessQuery.java, scg-system/src/main/java/io/telicent/access/AccessQueryResults.java, scg-system/src/main/java/io/telicent/access/FMod_AccessQuery.java, scg-system/src/main/java/io/telicent/access/services/AccessQueryService.java, scg-system/src/main/java/io/telicent/access/servlets/AccessQueryServlet.java, scg-system/src/main/java/io/telicent/backup/services/DatasetBackupService.java, scg-system/src/main/java/io/telicent/backup/utils/BackupUtils.java, scg-system/src/main/java/io/telicent/core/SmartCacheGraph.java, scg-system/src/main/java/io/telicent/labels/servlets/LabelsQueryServlet.java, scg-system/src/main/java/io/telicent/utils/ServletUtils.java, scg-system/src/main/java/io/telicent/utils/SmartCacheGraphException.java, scg-system/src/test/files/access-query-data-labelled-ds1.trig, scg-system/src/test/files/access-query-data-labelled-ds2.trig, scg-system/src/test/files/access-query-data-labelled.trig, scg-system/src/test/files/access-query-test-attribute-store.ttl, scg-system/src/test/files/access-query-test-config.ttl, scg-system/src/test/java/io/telicent/access/TestAccessQueryService.java
This PR adds an endpoint at `/$/access/query` which accepts POST requests containing a subject and predicate and returns the same subject and predicate, plus an objects property which either contains an array of the object values for any triples that match that match the subject and predicate, or null if there is nothing found or the user has no access to the information.
=> CORE-738: adding ability to query triple access

docs/access-queries.md, docs/index.md
This documentation relates to the work done in [CORE-738](https://telicent.atlassian.net/browse/CORE-738), [CORE-743](https://telicent.atlassian.net/browse/CORE-743) and [CORE-772](https://telicent.atlassian.net/browse/CORE-772).
[CORE-738]: https://telicent.atlassian.net/browse/CORE-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-743]: https://telicent.atlassian.net/browse/CORE-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-772]: https://telicent.atlassian.net/browse/CORE-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding documentation for access queries API

docs/access-api.yaml, scg-system/src/main/java/io/telicent/access/services/AccessQueryService.java
Testing these functions in Sys-Int showed up a `HTTP ERROR 500 java.lang.RuntimeException: org.apache.jena.dboe.transaction.txn.TransactionException: Not in a transaction`, so adding them to a read transaction.
=> Add read transactions to access query methods

.github/dependabot.yml
Occassionally we get Dependabot PRs that aren't individually mergeable because taking a minor version bump in one dependency is incompatible with a minor/patch version in another, and they should be bumped together.  This aligns our Dependabot configuration with other repositories to reduce this possibility going forward.
E.g #200 and #201 should be combined because individually those dependency bumps don't work, but when applied together they do
=> Combine minor and patch versions in Dependabot PRs

scg-system/src/main/java/io/telicent/access/servlets/AccessQueryServlet.java, scg-system/src/test/java/io/telicent/access/TestAccessQueryService.java
Addresses issue with missing request body causing 500 errors as reported in [CORE-791](https://telicent.atlassian.net/browse/CORE-791) and also handles an unparseable request body.
[CORE-791]: https://telicent.atlassian.net/browse/CORE-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CORE-791: improving error handling for access query requests

docs/access-api.yaml, scg-system/src/main/java/io/telicent/access/servlets/AccessTriplesServlet.java, scg-system/src/main/java/io/telicent/model/JsonTripleObject.java, scg-system/src/main/java/io/telicent/model/TypedObject.java, scg-system/src/test/files/access-query-data-labelled-ds1.trig, scg-system/src/test/java/io/telicent/access/TestAccessTriplesService.java
This PR adds language support to the triple access query. As language tagged strings are always of type `http://www.w3.org/1999/02/22-rdf-syntax-ns#langString` there is no requirement for the user to supply the datatype and therefore the language and datatype properties of the object have been made mutually exclusive.
=> CORE-799: adding support for language to triple access queries

docs/labels-api.yaml, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQuery.java
This is a follow up to https://github.com/telicent-oss/smart-cache-graph/pull/229 (CORE-837) as the API docs and tests were still not fully aligned to the implementation. The previous PR modified the request triple `object` value to be a JSON object but it turns out we were also missing the `triples` array wrapper to allow for multiple triples to be queried at once. This PR corrects this. The tests cases have also been modified to remove the `dataType` when the object is a URI. 
We should consider using something like [swagger-core](https://github.com/swagger-api/swagger-core) to generate our API docs as part of the build process and save us having to remember to and do this manually. I realise these things take a while to set up, but I think it would save us time in the long run!
=> Updating API docs to match implementation

pom.xml, scg-benchmark/src/main/java/io/telicent/core/LabelParsingBenchMark.java, scg-benchmark/src/main/java/io/telicent/core/SCGBenchmark.java, scg-system/src/main/java/io/telicent/core/FKProcessorSCG.java, scg-system/src/main/java/io/telicent/labels/TripleLabels.java, scg-system/src/test/java/io/telicent/TestFKProcessorSCG.java, scg-system/src/test/java/io/telicent/TestYamlConfigParserAuthz.java, scg-system/src/test/java/io/telicent/backup/services/TestBackupAndRestore.java, scg-system/src/test/java/io/telicent/core/TestInitialCompaction.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQueryService.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQueryServiceRocksDB.java
And benchmarking for the explicit parsing change in FKProcessorSCG. 
Have also tested this in greater depth for preformance and backwards compatibility for bacup/restore within the RocksDB  (see https://github.com/telicent-oss/rdf-abac/pull/120 and https://github.com/telicent-oss/rdf-abac/pull/114 )
=> [Minor] Upgrading to v1.0.2 RDF ABAC 

scg-system/src/main/java/io/telicent/backup/utils/BackupUtils.java, scg-system/src/test/java/io/telicent/backup/TestBackupData.java, scg-system/src/test/java/io/telicent/backup/services/TestDatasetBackupService.java, scg-system/src/test/java/io/telicent/backup/utils/TestBackupUtils.java
Also added some tests with multiple entries. 
Added description to some tests too.
**Note**: might revisit this further as -1 as a return value in error cases feels incorrect. We might end up creating a "-1.zip". An esoteric Runtime exception would probably serve better.
=> [CORE-854] Fixing the "next number" logic to factor in the compressed data files not just folders.

pom.xml, scg-benchmark/pom.xml, scg-server/pom.xml
```
[WARNING] JAR will be empty - no content was marked for inclusion!
```
We only build and use the test jar in SCG System so will disable it (and subsequently remove the warnings) in the affected submodules.
---
```
[WARNING] commons-logging-1.3.5.jar, jcl-over-slf4j-2.0.17.jar define 5 overlapping classes: 
[WARNING]   - org.apache.commons.logging.Log
[WARNING]   - org.apache.commons.logging.LogConfigurationException
[WARNING]   - org.apache.commons.logging.LogFactory
[WARNING]   - org.apache.commons.logging.impl.NoOpLog
[WARNING]   - org.apache.commons.logging.impl.SimpleLog
[WARNING] maven-shade-plugin has detected that some files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the file is copied to the uber jar.
[WARNING] Usually …
```
=> [Minor] Addressing some annoying WARNINGS in the maven build

scg-system/src/main/java/io/telicent/backup/services/DatasetBackupService.java, scg-system/src/test/java/io/telicent/backup/TestBackupData.java, scg-system/src/test/java/io/telicent/backup/services/TestDataSetBackupServiceUtils.java, scg-system/src/test/java/io/telicent/backup/services/TestDatasetBackupService.java
Plus made it clear the original measurements are in bytes and milliseconds.
Hopefully we never use hours - didn't think days would be possible. Similarly, Petabytes seem like they would cause all manner of issues, so cut it off there.
=> [CORE-867] Tweaking size and time measurements to be human-readable

README.md, scg-docker/docker-run.sh, scg-docker/latest-docker-run.sh, scg-system/src/test/java/io/telicent/core/TestInitialCompaction.java
I've removed a test that fails in the build due in part to it accidentally passing in the past (due to race conditions) and because of pre-existing configurations locally. 
Long story short - when the server starts up it compacts the jena DB. For obvious performance reasons, we do not carry out the compaction if (a) there is no size difference (b) if the folders don't yet exist. This test predates that and expects it to call compact() on start-up.
=> [Minor] Fixing docker scripts to run without maven.

CHANGELOG.md, scg-system/src/main/java/io/telicent/utils/ServletUtils.java, scg-system/src/test/java/io/telicent/backup/services/TestBackupAndRestoreWithEncryption.java, scg-system/src/test/java/io/telicent/core/TestInitialCompaction.java, scg-system/src/test/java/io/telicent/labels/services/TestLabelsQuery.java
If the JSON response contains Unicode characters that require more than one byte to represent them in UTF-8 then we were declaring the `Content-Length` incorrectly which led to Jetty aborting the request.  Now we don't declare it at all, Jetty might add it for us, but it isn't required.
=> Don't declare Content-Length for JSON

docs/backups-api.yaml
Adds a description of the details operation ([CORE-642](https://telicent.atlassian.net/browse/CORE-642)), makes notice of the possibility to omit the restoreID ([CORE-812](https://telicent.atlassian.net/browse/CORE-812)), and adds the "backup-success" field to restore response, which is a consequence of the immediate backup ([CORE-634](https://telicent.atlassian.net/browse/CORE-634)).
[CORE-642]: https://telicent.atlassian.net/browse/CORE-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-812]: https://telicent.atlassian.net/browse/CORE-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-634]: https://telicent.atlassian.net/browse/CORE-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> [CORE-901] - Backup - documentation update for CORE 634, 642, and 812

CHANGELOG.md, README.md, pom.xml, scg-benchmark/pom.xml, scg-docker/pom.xml, scg-server/pom.xml, scg-system/pom.xml, scg-system/src/main/java/io/telicent/core/FMod_InitialCompaction.java, scg-system/src/main/java/io/telicent/core/SPARQL_Update_CQRS.java, scg-system/src/main/java/io/telicent/core/SmartCacheGraph.java, scg-system/src/main/java/io/telicent/core/auth/FMod_JwtServletAuth.java, scg-system/src/main/java/io/telicent/core/auth/FusekiJwtAuthFilter.java, scg-system/src/main/java/io/telicent/core/auth/FusekiJwtConfigAdaptor.java, scg-system/src/main/java/io/telicent/core/auth/SCG_AuthPolicy.java, scg-system/src/main/java/io/telicent/core/auth/ServletAuthorizationContext.java, scg-system/src/main/java/io/telicent/core/auth/ServletAuthorizationEngine.java, scg-system/src/main/java/io/telicent/core/auth/TelicentAuthorizationFilter.java, scg-system/src/main/java/io/telicent/core/auth/UserInfoFilter.java, scg-system/src/test/java/io/telicent/AbstractBearerAuthTests.java, scg-system/src/test/java/io/telicent/LibTestsSCG.java, scg-system/src/test/java/io/telicent/MockKeyServer.java, scg-system/src/test/java/io/telicent/TestJwtServletAuth.java, scg-system/src/test/java/io/telicent/TestPersistentSetup.java, scg-system/src/test/java/io/telicent/access/TestAccessBase.java, scg-system/src/test/java/io/telicent/backup/TestBackupData.java, scg-system/src/test/java/io/telicent/backup/utils/TestBackupUtils.java, scg-system/src/test/java/io/telicent/core/TestInitialCompaction.java, scg-system/src/test/java/io/telicent/core/auth/TestSCGAuthPolicyGeneration.java, scg-system/src/test/java/io/telicent/core/auth/TestServletAuthorizationEngine.java, scg-system/src/test/java/io/telicent/core/auth/TestUserInfoFilter.java
This PR used the new functionality from telicent-oss/smart-caches-core#196 to implement roles and permissions based authorisation for SCG.
`FMod_JwtServletAuth` will not also register additional filters for User Info enrichment of requests and authorisation policy enforcement.  Since SCG can be dynamically configured with different datasets the policies are automatically generated based upon the datasets configured for the Fuseki instance.  Dataset endpoints are mapped to roles and permissions based upon their registered Fuseki `Operation`.  Telicent specific endpoints provided by our various Fuseki modules also have suitable policies generated.  Requests to unknown endpoints fallback to a default policy with is `DENY_ALL`.
Unit and integration tests are updated so that the fake JWTs we …
=> Add and enforce Telicent Authorisation Policies (CORE-962)
